// <auto-generated />
namespace WebApp4.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Initialize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialize));
        
        string IMigrationMetadata.Id
        {
            get { return "201304220859173_Initialize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
